Added `before_command` and `after_command` parameters
tbrand/neph pull request #72
Opened 2018-07-18 08:28 UTC by notramo

Also, removed `directory` and `environment` parameters, because the `before_command` parameter can be used to change directory or set environment.

2018-07-18 14:39 UTC, waghanza commented
@notramo I can see that `before_command` ans `after_command` are **singular** (and `String`).

I think having some `Array of String` is more flexible nop ?

2018-07-19 05:14 UTC, notramo commented
`before_command` and `after_command` are prepended/appended to the command using `String` concatenation. How do you append an `Array`  to a `String` without joining its elements into a `String`? And if the elements would be joined isn't it simpler to use a `String`? How would you use an `Array`?

2018-07-19 06:59 UTC, tbrand requested changes
Please do not remove directory parameter.
Even if we can change directory in before_command, directory parameter is smarter than it.

2018-07-19 17:33 UTC, notramo commented
@tbrand why is `directory` smarter?
It can do less things than `before_command` e.g.
```elvish
cd $E:BUILD_DIRECTORY
```
or
```elvish
if (eq $E:BUILD_IN_SOURCE_TREE $false) {
  cd build/
} else {
  # Build in source tree
  cd src/
}

2018-07-20 11:54 UTC, tbrand commented
For example, docker also support `WORKDIR` even if we can use `RUN cd some_directory`.

2018-07-20 12:02 UTC, notramo commented
@tbrand but what are the disadvantages? Could you provide an example?

2018-07-20 12:39 UTC, tbrand commented
Just for UX. `directory` is clearer for uses who want to set working directory.
Will you want users to write the working directory, environment variables and some other commands in `before_command`?

Also `before_command` and `after_command` should accept an array of String as waghanza said.

2018-07-20 12:43 UTC, waghanza commented
In my opinion, `directory` **SHOULD** be kept.

`before_command` and `after_command` **COULD** be use to change directory, btw
but `directory` is clearer and fit only for this usage

More, this let user choose ;-)

2018-08-11 13:26 UTC, waghanza commented
@notramo @tbrand when do you plan to release this feature ?

2018-08-11 14:04 UTC, tbrand commented
Is it needed for the benchmarker asap?

2018-08-11 14:12 UTC, waghanza commented
Asap, no 😊

I can not producer any code before the 27 of August, but for the next big step, it'll be helpful

2018-08-11 23:18 UTC, notramo commented
@waghanza I'm sorry, but @tbrand destroyed all my work on this project without even knowing what he is doing. This PR is based on my rewritten version of this software, but it can't be merged, because @tbrand reverted my improvements. Maybe he want to implement this feature in the old version. I don't want to work on this project if my work is not valued.
If my improvements will be restored, the PR could be merged. But doing it in Git is a pain. The project's Git repo is a mess. It is a pain to manage it in Git when there are better version control systems, for example [Pijul](https://pijul.com/).

2018-08-11 23:30 UTC, waghanza commented
@tbrand @notramo This project is very valuable for the benchmarking project we have.

I know that we (as developpers) can have different points of view, but we just have to see the main purpose

@notramo Working with git for about 5 years, I know this tool could be complications, but unless using `--hard` switch, everything is recoverable

2018-08-12 15:21 UTC, notramo commented
@waghanza yes, it is recoverable, but it is very hard.

2018-08-12 16:09 UTC, waghanza commented
@notramo @tbrand This situation is not helpful, I do not know what was done, but `neph` is very valuable for our **benchmark** project.

The most important feature needed, for me, is a way to set-up environnement (and open database if needed) - what was implemented with `before_command` - and to tear-down environnement (and close database if needed) - what was implemented with `after_command`.

I hope that will be done / re-implemented / recovered comprising everyone's work :heart:

2018-08-29 10:43 UTC, notramo commented
Since @tbrand shows no activity since reverting my improvements, and this PR is based on my redesigned code, I will close it.

2018-08-29 10:43 UTC, closed without merging